# Generated by Django 4.2.5 on 2023-11-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_addcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcar',
            name='car_image1',
            field=models.ImageField(default='car_image.jpg', upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='addcar',
            name='car_image2',
            field=models.ImageField(default='car_image.jpg', upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='addcar',
            name='car_image3',
            field=models.ImageField(default='car_image.jpg', upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='addcar',
            name='car_image4',
            field=models.ImageField(default='car_image.jpg', upload_to='car_image'),
        ),
        migrations.AddField(
            model_name='addcar',
            name='car_image5',
            field=models.ImageField(default='car_image.jpg', upload_to='car_image'),
        ),
        migrations.AlterField(
            model_name='addcar',
            name='car_image',
            field=models.ImageField(default='car_image.jpg', upload_to='car_image'),
        ),
    ]
