# Generated by Django 4.2.5 on 2023-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_person_name', models.CharField(max_length=100)),
                ('car_images', models.ImageField(default='car_image.jpg', upload_to='car_images')),
                ('car_images1', models.ImageField(default='car_image.jpg', upload_to='car_images1')),
                ('car_images2', models.ImageField(default='car_image.jpg', upload_to='car_images2')),
                ('car_images3', models.ImageField(default='car_image.jpg', upload_to='car_images3')),
                ('car_images4', models.ImageField(default='car_image.jpg', upload_to='car_images4')),
                ('car_images5', models.ImageField(default='car_image.jpg', upload_to='car_images5')),
            ],
        ),
    ]
