# Generated by Django 4.2.5 on 2023-11-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
