# Generated by Django 4.2.5 on 2023-11-03 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0014_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image.jpg', upload_to='image')),
                ('image1', models.ImageField(default='image.jpg', upload_to='image1')),
                ('image2', models.ImageField(default='image.jpg', upload_to='image2')),
                ('image3', models.ImageField(default='image.jpg', upload_to='image3')),
                ('image4', models.ImageField(default='image.jpg', upload_to='image4')),
                ('image5', models.ImageField(default='image.jpg', upload_to='image5')),
                ('person_name', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
