# Generated by Django 4.2.5 on 2023-11-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_alter_image_person_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
