# Generated by Django 4.2.5 on 2023-12-25 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_alter_addcar_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='car_code',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
